Mythril_Mirror/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('sheets.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),  # new
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/', include('api.urls')),
]

accounts/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
]

api/urls.py
from django.urls import path

from api.views import CharacterList, CharacterDetail

urlpatterns = [
    path('sheets/', CharacterList.as_view(), name='sheets-list'),
    path('sheets/<int:pk>', CharacterDetail.as_view(), name='sheets-detail')
]

sheets/urls.py
from django.urls import path

from . import views

app_name = 'sheets'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
]

api/models.py
from django.db import models

# Create your models here.

sheets/models.py
from django.db import models
import datetime
from django.utils import timezone


# Create your models here.


class Character(models.Model):
    name = models.CharField(max_length=25)
    level = models.IntegerField()
    race_choices = [
        ('Drow', 'Drow'),
        ('Dwarf', 'Dwarf'),
        ('Elf', 'Elf'),
        ('Half Elf', 'Half Elf'),
        ('Half Orc', 'Half Orc'),
        ('Halfling', 'Halfling'),
        ('Human', 'Human'),
        ('Warforged', 'Warforged')
    ]
    main_class_choices = [
        ('Barbarian', 'Barbarian'),
        ('Bard', 'Bard'),
        ('Cleric', 'Cleric'),
        ('Druid', 'Druid'),
        ('Fighter', 'Fighter'),
        ('Monk', 'Monk'),
        ('Paladin', 'Paladin'),
        ('Ranger', 'Ranger'),
        ('Rogue', 'Rogue'),
        ('Sorcerer', 'Sorcerer'),
        ('Warlock', 'Warlock'),
        ('Wizard', 'Wizard')
    ]
    race = models.CharField(choices=race_choices,
                            max_length=25, default='Human')
    main_class = models.CharField(
        choices=main_class_choices, max_length=25, default='Fighter')
    created = models.DateTimeField('created')

    def __str__(self):
        return self.name

    def was_created_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.created <= now

accounts/views.py
from django.shortcuts import render

# Create your views here.
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

api/views.py
from django.shortcuts import render
from rest_framework.views import APIView
from rest_framework.response import Response
from django.shortcuts import get_object_or_404
from sheets.models import Character
from api.serializers import CharacterSerializer
# Create your views here.


class CharacterList(APIView):
    def get(self, request):
        characters = Character.objects.all()[:20]
        data = CharacterSerializer(characters, many=True).data
        return Response(data)


class CharacterDetail(APIView):
    def get(self, request, pk):
        character = get_object_or_404(Character, pk=pk)
        data = CharacterSerializer(character).data
        return Response(data)

sheets/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from .models import Character
from django.urls import reverse
from django.views import generic
from django.utils import timezone


class IndexView(generic.ListView):
    template_name = 'sheets/index.html'
    context_object_name = 'recent_char_list'

    def get_queryset(self):
        return Character.objects.filter(created__lte=timezone.now()).order_by('-created')


def detail(request, character_id):
    character = get_object_or_404(Character, pk=character_id)
    return render(request, 'sheets/detail.html', {'character': character})


class DetailView(generic.DetailView):
    model = Character
    template_name = 'sheets/detail.html'

sheets/templates/partials/card.html
<div class="card mb-3">
  <h5 class="card-header ">{{ page.title }}</h5>
  <div class="card-body border-dark">
    <p class="card-text text-dark">
      {{ page.content|truncatewords_html:30 }}
      <hr>
      <div class="text-right"><a href="{% url 'wiki-details-page' page.slug %}" title="Read More">Read More</a></div>
  </div>
  <div class="card-footer">
    <small class="text-muted">Last updated {{ page.modified|date:"SHORT_DATETIME_FORMAT" }} by <b>{{ page.author.username }}</b></small>
  </div>
</div>

sheets/templates/sheets/detail.html
<h1>{{ character.name }}</h1>
<h2>Level: {{ character.level }} | {{ character.race }} | {{ character.main_class }}</h2>

sheets/templates/sheets/index.html
{% extends "base.html" %}

{% block content %}


{% if recent_char_list %}
<ul>
    {% for character in recent_char_list %}
    <li><a href="{% url 'sheets:detail' character.id %}">{{ character.name }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No sheets are available.</p>
{% endif %}
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <script src="https://kit.fontawesome.com/e7c15fdb77.js" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="shortcut icon"
    href="https://www.makeschool.com/assets/favicon_50x50-68cece25ffd4ff9e6545769d8a525b9ba532d432318c94e33fca9b96edb8cf6a.png"
    type="image/x-icon">
  <link rel="stylesheet" href="/static/style.css">
  <title>Mythril Sheets</title>
</head>

<body>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'sheets:index' %}"><i class="far fa-tired"></i></i> Mythril Mirror</a>
    <form class="form-inline ml-auto">
      {% if user.is_authenticated %}
      <div class="text-white">Hello, <strong>{{user.username | title}}</strong>!</div>
      <a href="/accounts/logout" class="btn btn-danger ml-2">Log Out</a>
      {% else %}
      <a href="/accounts/login" class="btn btn-secondary ml-2">Log In</a>
      {% endif %}
      {% if not user.is_authenticated %}

      <a href="/accounts/signup" class="btn btn-primary ml-2">Sign Up</a>
      {% endif %}

    </form>
  </nav>
  <main role="main" class="container" style="margin-top: 4vh;">
    {% block content %}
    <div class="row">
      <div class="col m-4">
        <div class="alert alert-warning" role="alert">
          If you see this, you forgot <code>{% verbatim %}{% block content %}{% endblock %}{% endverbatim %}</code> in
          your child template.
        </div>
      </div>
    </div>
    {% endblock %}
  </main>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous">
    </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">
    </script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous">
    </script>
</body>